module.exports={
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    GROUP_CHAT_COLLECTION:'groupchat',
    JOB_COLLECTION:'jobportal',
    MENTOR_COLLECTION:'mentorship',
    INTERN_COLLECTION:'internship',
    POST_COLLECTION: 'posts',
    DELETED_GROUP_CHAT_COLLECTION: 'deletedgroupchat',
    ONE_ON_ONE_CHAT_COLLECTION: 'oneononechat',
    DELETED_ONE_ON_ONE_CHAT_COLLECTION: 'deleteoneononechat',
    TIME_UNREAD_COLLECTION:'timestampunread',
    ONE_CHAT_FIRST_CHAT_DETAILS : 'onechatfirstchatdetails',
    LOG_DETAILS_COLLECTION: 'logdetails',
    ADMIN_LOG_DETAILS_COLLECTION: 'adminlog',
    ADMIN_BROADCAST_ALL : 'admin_broadcast_message',
    DELETED_ADMIN_BROADCAST : 'deleted_admin_broadcasts',
    ADMIN_CHAT_ENTRY_HISTORY : 'admin_chat_entry_history',
    SUPER_ADMIN_COLLECTION : 'superadmin',
    ACCOUNT_DISABLE_USER_LOGS : 'account_disable_user_logs',
    USER_PROFILE_VIEW_OTHERUSER : 'user_profile_view_otheruser',
    USER_REPORTS_REPORTED : 'user_reports_reported',
    USER_BLOCKS_LOGS : 'user_block_logs',
    UNBLOCK_BLOCK_LOG : 'unblock_block_log',
    ADMIN_ASK_QUESTION : 'admin_asked_question_log',
    CHAT_BACK_AND_FORTH_BOOK : 'chatbackandforthbook',
    CHAT_BACK_AND_FORTH_BOOK_ADMIN : 'chatbackandforthbookadmin',
    TIME_UNREAD_COLLECTION_ADMIN :'timestampunreadadmin',
    ONE_CHAT_FIRST_CHAT_DETAILS_ADMIN : 'onechatfirstchatdetailsadmin',
    ONE_ON_ONE_CHAT_COLLECTION_ADMIN: 'oneononechatadmin',
    NOTIFICATION_COLLECTION : 'notifications',
    ADMIN_PRIVATECHAT_VIEW_USER_NOTIFY : 'adminprivatechatviewusernotify',
    USER_MENTOR_COLLECTION : 'user_mentor_collection',
    FULL_NOTIFICATION_COLLECTION : 'full_notifications'
}
